# Generated by Django 2.0 on 2020-03-25 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Competence')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('qualification', models.CharField(choices=[('primary_vocational_education', 'Primary vocational education'), ('secondary_vocational_education', 'Secondary vocational education'), ('bachelor', 'Bachelor'), ('specialist', 'Specialist'), ('master', 'Master')], max_length=1024)),
                ('education_form', models.CharField(choices=[('internal', 'Internal'), ('extramural', 'Extramural')], max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOfStudyWorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Competence')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.FieldOfStudy')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorWorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge', models.CharField(max_length=1024)),
                ('skills', models.CharField(max_length=1024)),
                ('proficiency', models.CharField(max_length=1024)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Competence')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('value', models.IntegerField(blank=True, default=0, null=True, verbose_name='Значение')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='OutcomesOfWorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterylevel', models.CharField(choices=[('1', 'low'), ('2', 'average'), ('3', 'high')], default=1, max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Items')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisitesOfWorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterylevel', models.CharField(choices=[('1', 'low'), ('2', 'average'), ('3', 'high')], default=1, max_length=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.FieldOfStudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.FieldOfStudy')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1024, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('discipline_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.DisciplineSection')),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('hoursFirstSemester', models.IntegerField(blank=True, null=True)),
                ('hoursSecondSemester', models.IntegerField(blank=True, null=True)),
                ('goals', models.CharField(max_length=1024)),
                ('result_goals', models.CharField(max_length=1024)),
                ('field_of_studies', models.ManyToManyField(through='workprogramsapp.FieldOfStudyWorkProgram', to='workprogramsapp.FieldOfStudy')),
                ('outcomes', models.ManyToManyField(related_name='WorkProgramOutcomes', through='workprogramsapp.OutcomesOfWorkProgram', to='workprogramsapp.Items')),
                ('prerequisites', models.ManyToManyField(blank=True, null=True, related_name='WorkProgramPrerequisites', through='workprogramsapp.PrerequisitesOfWorkProgram', to='workprogramsapp.Items')),
            ],
        ),
        migrations.AddField(
            model_name='routecomposition',
            name='work_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='route',
            name='work_programs',
            field=models.ManyToManyField(through='workprogramsapp.RouteComposition', to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='prerequisitesofworkprogram',
            name='workprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='outcomesofworkprogram',
            name='workprogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='indicatorworkprogram',
            name='work_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='work_programs',
            field=models.ManyToManyField(through='workprogramsapp.IndicatorWorkProgram', to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='fieldofstudyworkprogram',
            name='work_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='disciplinesection',
            name='evaluation_tools',
            field=models.ManyToManyField(to='workprogramsapp.EvaluationTool'),
        ),
        migrations.AddField(
            model_name='disciplinesection',
            name='work_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.WorkProgram'),
        ),
        migrations.AddField(
            model_name='competenceindicator',
            name='field_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.FieldOfStudy'),
        ),
        migrations.AddField(
            model_name='competenceindicator',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workprogramsapp.Indicator'),
        ),
        migrations.AddField(
            model_name='competence',
            name='field_of_study',
            field=models.ManyToManyField(to='workprogramsapp.FieldOfStudy'),
        ),
        migrations.AddField(
            model_name='competence',
            name='indicators',
            field=models.ManyToManyField(through='workprogramsapp.CompetenceIndicator', to='workprogramsapp.Indicator'),
        ),
        migrations.AddField(
            model_name='competence',
            name='work_program',
            field=models.ManyToManyField(to='workprogramsapp.WorkProgram'),
        ),
        migrations.AlterUniqueTogether(
            name='routecomposition',
            unique_together={('route', 'user', 'work_program', 'field_of_study')},
        ),
        migrations.AlterUniqueTogether(
            name='indicatorworkprogram',
            unique_together={('competence', 'work_program', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldofstudyworkprogram',
            unique_together={('competence', 'work_program', 'field_of_study')},
        ),
        migrations.AlterUniqueTogether(
            name='competenceindicator',
            unique_together={('competence', 'indicator', 'field_of_study')},
        ),
    ]
