# Generated by Django 2.0 on 2020-03-25 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='author',
        ),
        migrations.AlterField(
            model_name='outcomesofworkprogram',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Items'),
        ),
        migrations.AlterField(
            model_name='prerequisitesofworkprogram',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Items'),
        ),
        migrations.AlterField(
            model_name='workprogram',
            name='outcomes',
            field=models.ManyToManyField(related_name='WorkProgramOutcomes', through='workprogramsapp.OutcomesOfWorkProgram', to='dataprocessing.Items'),
        ),
        migrations.AlterField(
            model_name='workprogram',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='WorkProgramPrerequisites', through='workprogramsapp.PrerequisitesOfWorkProgram', to='dataprocessing.Items'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
