# Generated by Django 2.0 on 2020-03-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workprogramsapp', '0002_auto_20200325_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogram',
            name='guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workprogram',
            name='list_of_references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
