# Generated by Django 2.0 on 2020-02-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('user', models.ManyToManyField(related_name='domain_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('value', models.IntegerField(blank=True, default=0, null=True, verbose_name='Значение')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
                ('domain', models.ForeignKey(blank=True, help_text='Укажите область', null=True, on_delete=django.db.models.deletion.CASCADE, to='dataprocessing.Domain', verbose_name='Область знаний')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('0', 'неопределенное'), ('1', 'включает в себя'), ('2', 'относится к'), ('3', 'является пререквизитом для'), ('4', 'имеет пререквизит'), ('5', 'тождество'), ('6', 'являются частями одного раздела'), ('7', 'отсутствует')], default='1', max_length=10, verbose_name='Связь')),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item1', to='dataprocessing.Items', verbose_name='Элемент РПД')),
                ('item2', models.ManyToManyField(related_name='item2', to='dataprocessing.Items', verbose_name='Элемент РПД')),
            ],
        ),
    ]
